# Generated by Django 5.1.4 on 2025-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'draft'), ('PU', 'pulished'), ('DI', 'disable')], default='pulished', max_length=2),
        ),
    ]
