# Generated by Django 5.1.4 on 2025-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'draft'), ('PU', 'published'), ('DI', 'disable')], default='PU', max_length=2),
        ),
    ]
