# Generated by Django 5.1.4 on 2025-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED'), ('disable', 'DISABLE')], default='published', max_length=10),
        ),
    ]
